### ISSUE TITLE
网易云音乐无法加载

### ISSUE THREAD

**Issue by Pidbid** [liwanglin12/Hermit-X#166]
lwl你好，现在是2021年年末，我还在使用着HermitX，由于本人从2017年开始就使用了，到2021年。之前使用都很愉快，但是最近几个月，网易云已经无法播放了。在每一篇文章后面添加我喜欢的歌曲已经成为一个我很喜欢的习惯，但是最近突然不能用很困惑。希望你有时间的话请抽空更新一下吧，万分感谢
From wicos

**Comment by syhily** [comment]
手动升级 Meeting API 即可。
