### ISSUE TITLE
Problem with Hermit-X's volume control bar

### ISSUE THREAD

**Issue by yexing17** [liwanglin12/Hermit-X#21]
Σ(ﾟдﾟ;)When I try to adjust the volume of Hermit-X,I find that bar is very intersting(°∀°)ﾉ

When the bar is clicked,it will no sound.And then the volume only changed by draging,and it's very hard to drag to turn up the sound.(〜￣△￣)〜

Hermit-X will be cuter if we can <del>flirt</del> adjust the volume bar(=・ω・=)

**Comment by liwanglin12** [comment]
@yexing17 @DIYgod

**Comment by liwanglin12** [comment]
@yexing17 This is Aplayer's design issue, please go https://github.com/DIYgod/APlayer/issues

**Comment by DIYgod** [comment]
It works well here.

Try [demo page](https://aplayer.js.org/) and tell me which browser are you using.

**Comment by yexing17** [comment]
Sorry,my bad.
I find it only occurs in my website,plyer works well in your demos.
My browser is Chrome55,maybe there are some problems with my website's setting.
Thanks for your reply

**Comment by liwanglin12** [comment]
http://www.hisun.me/tips_3/
![aptest.gif](https://ooo.0o0.ooo/2017/01/19/588059677e71e.gif)
TEST PASS

**Comment by yexing17** [comment]
Well,error only occurs in chrome/55.0.2883.87
<img src="http://oismqfoah.bkt.clouddn.com/img/test/chrome55_2.gif" style="max-width:100%;"/>
And also work well in Edge/14.14393
<img src="http://oismqfoah.bkt.clouddn.com/img/test/msedge.gif" style="max-width:100%;"/>
The bar only can't works well in my website with my chrome(´･_･`)

**Comment by liwanglin12** [comment]
I use Chrome 58.0.2989.0 canary (64-bit).
