### ISSUE TITLE
Some problems with Hermit-X's play mode on phone and pad

### ISSUE THREAD

**Issue by Minoyu** [liwanglin12/Hermit-X#22]
\^O^/Excuse me,I found something interesting in the player on my phone or ipad .
We choose a playlist mode to play music and when one song finished then it will stop and cannot continue to play the next one.
I feel confused about that . Also, auto play cannot use on phone.
Test by chrome 55.0 ,QQ Browser and UC
^ω^Thank you for creating such a perfect player

**Comment by liwanglin12** [comment]
@Minoyu That's a feature, not a bug. I complain this issue with @DIYgod so many times, but he insist on it that in mobile devices, player should not be able to autoplay or auto swith song. So I can't help you on this issue 😞 please contact @DIYgod at https://github.com/DIYgod/APlayer/issues. Thanks~
