### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by nazhenhuiyi** [liwanglin12/Hermit-X#25]
你们是怎么找到对应的 api地址,有什么黑科技吗?

**Comment by liwanglin12** [comment]
@nazhenhuiyi @metowolf

**Comment by nazhenhuiyi** [comment]
机器人???╭(╯^╰)╮

**Comment by metowolf** [comment]
抓包，下断点
![](http://ww2.sinaimg.cn/large/a15b4afegy1fd06xysh0mj21ag0g0q8s)

**Comment by nazhenhuiyi** [comment]
@metowolf 看来都是这种套路...
