### ISSUE TITLE
文章编辑时添加了 Hermit X ，发布之后看不到播放器

### ISSUE THREAD

**Issue by login926** [liwanglin12/Hermit-X#29]
>WordPress 4.7.3
>PHP 7.0.7
>Chrome 已禁用 uBlock Origin

文章中插入了 Hermit X
![](https://ooo.0o0.ooo/2017/03/28/58da4aba1cb6d.png)
但是文章发布之后看不到 Aplayer 播放器😂
![](https://ooo.0o0.ooo/2017/03/28/58da4b597cc93.png)
Chrome 调试：
![](https://ooo.0o0.ooo/2017/03/28/58da4b8236259.png)

所以是不是我哪里搞错了😂

**Comment by liwanglin12** [comment]
@login926 @DIYgod

**Comment by oyoulee** [comment]
遇到同样的问题，更新后不显示播放器了[http://i4.buimg.com/1949/a7179043170a6cd1.png](url)

**Comment by fly3949** [comment]
是否使用了pjax换页？
如果方便，能否提供地址？

Do you use PJAX loading?
Post your website address if it is possible .

**Comment by login926** [comment]
未使用 pjax ，Hermit X 版本为2.6.1.1210-RC
站点暂未绑定域名，现不方便公开地址。

**Comment by oyoulee** [comment]
http://www.0-v.vip/vip/index.php/2017/03/28/hermit-x/
拿去测试吧

**Comment by fly3949** [comment]
It seems that a f*cking mistake caused it.
@DIYgod is fixing it, just sit and relax.

**Comment by liwanglin12** [comment]
@oyoulee @login926 
Thanks for your information. Now We are already located the issue. We will fix it ASAP.

**Comment by liwanglin12** [comment]
https://github.com/liwanglin12/Hermit-X/commit/abb71cf18b5f1a04b3af7af7930b8de19b1c1104
Fixed.

**Comment by login926** [comment]
嗯，能用了，蟹蟹大佬🙃
