### ISSUE TITLE
pjax cant loading Hermit X after updata

### ISSUE THREAD

**Issue by 23330** [liwanglin12/Hermit-X#34]

**Comment by liwanglin12** [comment]
please provide your domain.
@DIYgod

**Comment by DIYgod** [comment]
@liwanglin12 加上 issue 规范吧：https://github.com/DIYgod/APlayer/issues/new

**Comment by liwanglin12** [comment]
@DIYgod 你是contributor不能加么

**Comment by 23330** [comment]
cant use when Load the page second time. u blog also like this

**Comment by liwanglin12** [comment]
@23330 Issue confirm. Please wait.

**Comment by fly3949** [comment]
Please post your error information form the console.
And please provide your website's address if it's possible.

**Comment by 23330** [comment]
lwl12.com blog also like this .cant Load when Load the page second time. 
fist load is normal

**Comment by liwanglin12** [comment]
fixed. https://github.com/liwanglin12/Hermit-X/pull/36

**Comment by 23330** [comment]
thx
