### ISSUE TITLE
之前说的到02:43自动停止的问题

### ISSUE THREAD

**Issue by yecl** [liwanglin12/Hermit-X#39]
![image](https://cloud.githubusercontent.com/assets/7091454/25078332/6afc61bc-2364-11e7-915d-791d2905ab72.png)

chrome 57

具体症状看https://yecl.net/nier-automata-b-ending.html

貌似和W3 Total Cache有那么一点关系（关了就没事），但是这错误信息看起来又和缓存没关系

**Comment by fly3949** [comment]
网易云 m7 的这个地址一直都有这个问题...
建议碰到 m7 就换 http 或者搞个反代什么的 orz
