### ISSUE TITLE
添加QQ音乐的播放地址，播放时候都提示Error happens ╥﹏╥

### ISSUE THREAD

**Issue by sunnywolf727** [liwanglin12/Hermit-X#40]
演示地址：https://home4love.com/4562.html

![20170417150636](https://cloud.githubusercontent.com/assets/26103903/25082728/3fd51d32-2385-11e7-8310-ea68cc64bdc9.png)

**Comment by liwanglin12** [comment]
Seems you are using local music source?

**Comment by fly3949** [comment]
Nothing wrong.
