### ISSUE TITLE
'资源加载策略' should allways setting '全局加载'

### ISSUE THREAD

**Issue by 23330** [liwanglin12/Hermit-X#41]
beacuse if user first open anyone post  without Hermit X function then open anyone post with Hermit X function ,the Hermit X function will do not work when the admin setting  按需加载 in his website

**Comment by 23330** [comment]
我忘了 PJAX网站才会这样 建议给'全局加载' 加个提示：建议PJAX网站启用

**Comment by liwanglin12** [comment]
我以为这个是常识来着……[哭笑]
