### ISSUE TITLE
移动端h5不能自动播放背景音乐！

### ISSUE THREAD

**Issue by cypcpycy** [liwanglin12/Hermit-X#42]
在移动端无法自动播放背景音乐，插件hermit就可以自动播，怎么破啊，求改进！

**Comment by 23330** [comment]
Hope this is enhancement will controllable.because i dont like autoplay on phone.

**Comment by liwanglin12** [comment]
列表自动播放下一首已解决，自动开始播放由于潜在的数据网络风险不予增加

**Comment by liwanglin12** [comment]
#56

**Comment by DullSky** [comment]
我能说这个是刚需吗，求可以手动设置自动播放，autoplay=true；毕竟连HTML5最原始的audio都支持啊

**Comment by Copay** [comment]
@DullSky 这可能是不可能的,如果您有了解这方面的开发的话,您会知道,目前移动浏览器端对自动播放有严格的限制.播放方法必须直接包含于某个用户事件中,否则浏览器将忽略该播放请求.

**Comment by DullSky** [comment]
网易云音乐和hermit就做到了啊

**Comment by liwanglin12** [comment]
他们是玩了一个tricks，把播放绑定在了用户触摸事件上。您可以自行调用APlayer API实现相同的效果。
我们不会直接提供移动端的自动播放支持。
