### ISSUE TITLE
Does not support https

### ISSUE THREAD

**Issue by 23330** [liwanglin12/Hermit-X#43]
this is my consolo.log：

Mixed Content: The page at 'https://xxx/' was loaded over HTTPS, but requested an insecure video 'http://m7.music.126.net/20170425230836/71c2cfe906d85dd3075e0c363419f14e/ymusic/9e69/0007/763a/684f3702cba883458d490f51b3f71788.mp3'. This content should also be served over HTTPS.

**Comment by liwanglin12** [comment]
Fixed. #47
