### ISSUE TITLE
music play before load about 2M 

### ISSUE THREAD

**Issue by 23330** [liwanglin12/Hermit-X#44]
Loading time and data too much .Especially for mobile phone users are not friendly enough.Expect improvement.

**Comment by liwanglin12** [comment]
@23330 I have no issue. Please check your network.

**Comment by 23330** [comment]
say 2M load paly beacause of see this blog https://xin.moe/mp3-cache-2mb-play/
Although the load on the computer very fast no feeling
But on the phone this load time before play,the delay is obvious
