### ISSUE TITLE
HermitX调用时出现按钮移位

### ISSUE THREAD

**Issue by SakuraLove** [liwanglin12/Hermit-X#45]
![qq 20170429093145](https://cloud.githubusercontent.com/assets/20598278/25551901/d230130c-2cbe-11e7-956c-e805cfa4f0f1.png)
已经更新至最新，一直都是出现了移位问题

**Comment by SakuraLove** [comment]
https://blog.sakuralove.cn/read/remade-a-home-page.html

**Comment by SakuraLove** [comment]
已经发现了，与Aplayer For WordPress插件css冲突吧

**Comment by liwanglin12** [comment]
。。。为什么要同时用俩
