### ISSUE TITLE
Playing for a long time will stop running

### ISSUE THREAD

**Issue by 23330** [liwanglin12/Hermit-X#51]
I often open my blog listen songs but play to a certain time will stop ,very unhappy
Sometimes the play soon stopped

**Comment by 23330** [comment]
Intermittently stop playing

**Comment by liwanglin12** [comment]
@23330 Please provide more infomation by F12 Console

**Comment by 23330** [comment]
Failed to load resource: net::ERR_INSECURE_RESPONSE m8.music.126.net/20170505024211/8422ed549915a9018a7a36c057ac259b/ymusic/2247/bf87/9fc5/ac4a531e4e62a9ca07f414f37c9030ea.mp3 
Failed to load resource: net::ERR_INSECURE_RESPONSEm8.music.126.net/20170505024616/2962689eaa0ff95220defcb6c3e5367c/ymusic/702a/9e98/a773/14c376e67c2f89d3a6bafb0e7865c8d7.mp3 
Uncaught (in promise) DOMException: Failed to load because no supported source was found. xx.com/:1

**Comment by 23330** [comment]
When I cut the song manually,my console log:

Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

**Comment by liwanglin12** [comment]
Do not contain two issues in one ticket. Thanks
We'll investigate this ASAP.
