### ISSUE TITLE
更新完放不出音乐了

### ISSUE THREAD

**Issue by 23330** [liwanglin12/Hermit-X#63]
回滚自己的备份正常播放,一更新就不行了。访问了下你的博客也是同样的情况,截图是你的关于页,chrome和firefox都是这样
![image](https://user-images.githubusercontent.com/23148629/27183267-a9740ed8-5210-11e7-89c0-43074bbca7cc.png)
F12:
![image](https://user-images.githubusercontent.com/23148629/27183286-b7195d86-5210-11e7-83de-114c6bc7c62b.png)

**Comment by liwanglin12** [comment]
@23330 We were known this issue before this time.
As we known, the issue is NOT caused by new version.
 Issue details are investigating by our team now.Please wait a moment.

**Comment by liwanglin12** [comment]
Update: issue is confirm now, we're fix it ASAP.
One more things, in previous comment I make a mistake, the issue is actually in the lastest version.

**Comment by liwanglin12** [comment]
Fixed. Please update to 2.6.4.1200-beta
